### ISSUE TITLE
event statistics analysis bug

### ISSUE THREAD

**Issue by tsheringde** [QutEcoacoustics/audio-analysis#142]
### Expected behaviour

To run event statistics for a given annotations csv file

### Actual behaviour

fatal error (as shown above)

### Steps to reproduce the behaviour

- What command did you use?
  - `PS C:\Release.17.12.270.3> ./AnalysisPrograms.exe eventstatistics -so "C:\Users\n8937087\Box Sync\SOUNDSCAPE\Heron Groun
dtruth data\heron latest annotations.csv" -co "C:\Release.17.12.270.3\ConfigFiles\EventStatistics.yml" -o "C:\Event statistics"`
- What config file did you use?
   `EventStatistics.yml`
- Where can we find the source data used?
  - [Heron Annotations verified.xlsx](https://github.com/QutBioacoustics/audio-analysis/files/1578114/Heron.Annotations.verified.xlsx)

### Any other details

```
[2017-12-21T16:02:47.4875441+10:00] FATAL - Unhandled exception ->
CsvHelper.CsvReaderException: No properties are mapped for type 'AnalysisPrograms.EventStatistics.ImportedEvent'.
   at CsvHelper.CsvReader.CreateFuncForObject(Type recordType)
   at CsvHelper.CsvReader.GetReadRecordFunc[T]()
   at CsvHelper.CsvReader.CreateRecord[T]()
   at CsvHelper.CsvReader.<GetRecords>d__65`1.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Acoustics.Shared.Csv.Csv.ReadFromCsv[T](Action`1 readerHook, TextReader stream) in C:\projects\audio-analysis\Acou
stics\Acoustics.Shared\Csv\Csv.cs:line 174
   at Acoustics.Shared.Csv.Csv.ReadFromCsv[T](FileInfo source, Boolean throwOnMissingField, Action`1 readerHook) in C:\p
rojects\audio-analysis\Acoustics\Acoustics.Shared\Csv\Csv.cs:line 148
   at AnalysisPrograms.EventStatistics.EventStatisticsEntry.<ExecuteAsync>d__3.MoveNext() in C:\projects\audio-analysis\
AudioAnalysis\AnalysisPrograms\EventStatistics\EventStatisticsEntry.cs:line 116
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at AnalysisPrograms.MainEntry.ExecuteAsync[T](Func`2 task, T arguments) in C:\projects\audio-analysis\AudioAnalysis\A
nalysisPrograms\Production\MainEntryUtilities.cs:line 111
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid2[T0,T1](CallSite site, T0 arg0, T1 arg1)
   at PowerArgs.ArgAction`1.Invoke() in c:\Work\Software Dev\Github\PowerArgs\PowerArgs\ArgAction.cs:line 38
   at AnalysisPrograms.MainEntry.Main(String[] args) in C:\projects\audio-analysis\AudioAnalysis\AnalysisPrograms\MainEn
try.cs:line 50
```

**Comment by atruskie** [comment]
@tsheringde, has been resolved at some point.

I tested it with the file you provided and I've sent you an email with the results.
